e) {
              result.errors.push(await new Promise((resolve) => logPluginError(e, name, note &&